### ISSUE TITLE
Restore IDrawingInfo type

### ISSUE THREAD

**Issue by thw0rted** [Esri/arcgis-rest-js#1007]
The old `arcgis-rest-types` package [exposed an interface](https://github.com/Esri/arcgis-rest-js/blob/master/packages/arcgis-rest-types/src/webmap.ts#L918) that describes the shape of [the drawingInfo field](https://esri.github.io/arcgis-rest-js/api/types/IDrawingInfo/) in a layer definition, even though the actual types under ILayerDefinition [failed to use it](https://github.com/Esri/arcgis-rest-js/blob/main/packages/arcgis-rest-feature-service/src/helpers.ts#L648).  `rest-feature-service` should expose that interface again, and ideally use it as the type of the `drawingInfo` field.

**Comment by thw0rted** [comment]
Just as a side note: it would be extra nice if somebody felt inclined to flesh out the missing parts of that old interface, like I had to make my own types to describe the `renderer` property, which has helpful `uniqueValueInfos` (which, themselves, needed a custom interface).

**Comment by patrickarlt** [comment]
@thw0rted ArcGIS REST JS is not and was never supposed to be a types library for ArcGIS. We generally implemented types when it was helpful for our own documentation for custom methods. When we had types included most of our issues ended up actually being about adding this type or that type when it was unrelated to the actual request/response process. See https://github.com/Esri/arcgis-rest-js/issues/668#issuecomment-608006590 for some of my thoughts on this.

It is also REALLY, REALLY hard to be an authoritative type library even if we wanted to. For example the old `IDrawingInfo` field is based on the [type in the web map specification](https://developers.arcgis.com/web-map-specification/objects/drawingInfo/) NOT the type returned by `getService()` or `addToServiceDefinition()` (the methods where `ILayerDefinition` is used). My best guess is that should be [the renderer documented in common data types](https://developers.arcgis.com/documentation/common-data-types/renderer-objects.htm). But the type of the `renderer` property isn't actually documented anywhere in an authoritative way.

In the end it seemed better to be broad rather then to act like the authoritative type library for everything. If you still need things from `arcgis-rest-types` nothing prevents you from installing v3 of it and importing what you need.

If you want to do a PR restoring the old `IDrawingInfo` and have `ILayerDefinition` I would accept it because `ILayerDefinition` is used by some of our methods.
