### ISSUE TITLE
FYI: existing type definitions

### ISSUE THREAD

**Issue by JeffJacobson** [Esri/arcgis-rest-js#107]
A while ago I contributed the [@types/arcgis-rest-api type definitions](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/arcgis-rest-api) to the DefinitelyTyped repository. If they meet your needs you could use these instead of creating them from scratch. (Available via NPM [here](https://www.npmjs.com/package/@types/arcgis-rest-api))

I have another version with additional types, but that hasn't been contributed yet. I've attached that version below, in case you want to use it.
[arcgis-rest-api.d.ts.zip](https://github.com/Esri/arcgis-rest-js/files/1674776/arcgis-rest-api.d.ts.zip)

(The only reason that all of the types are in a single `index.d.ts` file is simply because that's the way the DefinitelyTyped project expects them to be.)

**Comment by jgravois** [comment]
very cool! 

this is really similar to the [`arcgis-rest-common-types`](https://github.com/Esri/arcgis-rest-js/blob/f12822cf57e8ab7e41867f17b243d676045588d5/packages/arcgis-rest-common-types/src/index.ts) package we started stubbing out.

we could certainly link out and promote your additional typings, but my first instinct is that it'd be good to combine forces. would you be interested in that?

**Comment by JeffJacobson** [comment]
Yeah, that sounds good. Seems like it would be best to just copy the types I made into your project rather than linking out to the `@types` ones, so they would be kept all in a single location.

**Comment by tomwayson** [comment]
@JeffJacobson this is awesome - I'm starting to recreate some of these - and I don't want to.

No matter what we decide, I think the main thing is to eliminate any duplication of error.

I'll be the first to admit that I'm mystified by TS best practices, I thought DefinitelyTyped was out, and `npm i @types/whateves` was in. Now it appears you're telling me _they are the same thing_. 

 -->Mind blown<--

Also, we've prefixing all interfaces w/ `I`, but you haven't done that. What gives bro? I like yours better. Is that cool? Can we do that?

My only concerns w/ using DefinitelyTyped are how difficult is it to keep the types there up to date and how do update the types as you develop? Who merges PRs to DefinitelyTyped? I presume each of the libraries in this monorepo would add @types/arcgis-rest-api to their package.json files, but what do we do while we're developing - `npm link` to a local copy of DefinitelyTyped (again, you have to treat me like a child when it comes to TS). If those concerns aren't a big deal, I say that this library should depend on @types/arcgis-rest-api and start updating them as we need. That way whatever libraries already depend on those can benefit from the updates.

**Comment by tomwayson** [comment]
OK, wish I had done a quick google search on this before my previous comment. Turns out, [If your package is written in TypeScript then you should publish the types w/ your package](https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html), so I'm going to PR @JeffJacobson's types to arcgis-rest-common-types - at the very least the ones I'll need for the new package for managing features. Also I talked IRL w/ @jgravois and he prefer's the `I` prefix for interfaces, so I'll add that to the ones I bring over.

@JeffJacobson if we were to include _all_ of your types (not just the ones we need), would that be something you'd be willing to use in your projects instead of `@types/arcgis-rest-api`, even if their prefixed w/ `I`? I think it'd be great if we could just maintain one package going forward. Hopefully it would be easier for you to publish here than over at DefinitelyTyped. Ultimately I'd like to deprecate the former and update it's [dependents](https://www.npmjs.com/browse/depended/@types/arcgis-rest-api).

**Comment by JeffJacobson** [comment]
Sounds good.

**Comment by tomwayson** [comment]
closing as this was resolved in #121 - thanks again @JeffJacobson!
