### ISSUE TITLE
IE11 breaks w/o a fetch() polyfill even when supplying my own fetch() implementation

### ISSUE THREAD

**Issue by tomwayson** [Esri/arcgis-rest-js#108]
Based on #39, I would expect that if my app is running in some 💩 browser that doesn't support the frickin Internet, I could pass in an implementation of `fetch()` _without actually having to polyfill it_.

However the call to `.bind()` on this line requires a global `fetch()` to exist, regardless of whether or not you intend to use it:
https://github.com/Esri/arcgis-rest-js/blob/f12822cf57e8ab7e41867f17b243d676045588d5/packages/arcgis-rest-request/src/request.ts#L106

You're probably asking, "why not just conditionally polyfill `fetch()` for those unfortunate users?" [as I have suggested before](https://github.com/Esri/arcgis-rest-js/issues/34#issuecomment-326812183). Well, somehow, our app (the Hub), which has a metric ton of dependencies, has been supporting IE11 w/o a `fetch()` polyfill up until this point. That a) really surprises me, and b) makes me pause before adding them. I'll probably end up doing that in the short term, but wanted to raise this issue here and see if we wanted to allow consumers to use this library w/o a polyfill if they have a `fetch()` implementation

If so, do we want to do the same for for `Promise`?

**Comment by patrickarlt** [comment]
I'll tackle fixing this.

**Comment by tomwayson** [comment]
Thanks @patrickarlt but I think I can help, if not implement it myself - I have a real-world bug in our production app.

Really what I wanted to find out by opening this issue is to verify my assumptions: 
- we want to allow consumers to use this library w/o a polyfill if they have a `fetch()` implementation
- ditto for `Promise`

If that's the case I can make a PR w/ those

**Comment by patrickarlt** [comment]
@tomwayson the only reason we check for `Promise` is because `Promise` is required by `fetch`. So your custom `fetch` still needs to return a standard `Promise` which will you will still need a global `Promise` polyfill for.

If your custom `fetch` returns something "Promise-like" it can be a little hard to check for since you technically don't need promise but it could cause a lot of false positives.

Seeing that Babel and others require `Promise` polyfills anyway I kind of want to enforce a global `Promise` check.
