### ISSUE TITLE
check for error _before_ parsing response as JSON/text/whateves

### ISSUE THREAD

**Issue by tomwayson** [Esri/arcgis-rest-js#110]
It seems to me that we need a `response.ok` check before this `switch`:

https://github.com/Esri/arcgis-rest-js/blob/f12822cf57e8ab7e41867f17b243d676045588d5/packages/arcgis-rest-request/src/request.ts#L175-L190

The same way ember-arcgis-portal-services does here:

https://github.com/Esri/ember-arcgis-portal-services/blob/master/addon/mixins/service-mixin.js#L90-L108

What happens now is that the underlying HTTP error (404, 500, etc) gets buried by a JSON parsing error like `SyntaxError: Unexpected token < in JSON at position 0`, at least in the case of `f=json`.

See the first error on https://esri.github.io/ember-cli-cedar/#/error-handling as an example.

If y'all agree, I can PR the logic from ember-arcgis-portal-services.

**Comment by patrickarlt** [comment]
Seems reasonable to me.

**Comment by patrickarlt** [comment]
Since I had to know about why this happens according to https://www.tjvantoll.com/2015/09/13/fetch-and-errors/ and https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch#Checking_that_the_fetch_was_successful `fetch` only rejects the promise when a network error is encountered. So you still have to check `response.ok` and return a `Promise.reject(response)` if the response is not ok make this behave like most people will expect.
