### ISSUE TITLE
introduce support for aborting/timing out requests

### ISSUE THREAD

**Issue by jgravois** [Esri/arcgis-rest-js#114]
when i started exploring what it would look like for esri leaflet to use this lib i was reminded that we allow developers to pass their own (optional) timeout (ref: https://github.com/Esri/esri-leaflet/pull/730)

a `fetch` can also be aborted using the technique below (in [Edge](https://developer.mozilla.org/en-US/docs/Web/API/AbortController#Browser_compatibility) and [Firefox](https://developer.mozilla.org/en-US/docs/Web/API/AbortController#Browser_compatibility) anyway).

```js
const controller = new AbortController();
const signal = controller.signal;

setTimeout(() => controller.abort(), 5000);

fetch(url, { signal }).then(response => {
  return response.text();
}).then(text => {
  console.log(text);
});
```
  
https://developers.google.com/web/updates/2017/09/abortable-fetch

**Comment by tomwayson** [comment]
In ember-cli-cedar [we use Promise.race()](https://github.com/Esri/ember-cli-cedar/blob/3ab2e22b631d5866a5b6f2d94883129525da4281/addon/components/cedar-chart/component.js#L86). I always thought that was an RSVP-only thing, but looks like it [might be in other promise implementations](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/race)?

**Comment by patrickarlt** [comment]
@tomwayson `Promise.race()` is standard. @jgravois it would be trivial to do timeouts with `Promise.race()` and `timeeout` could just be another standard request option.

**Comment by patrickarlt** [comment]
@jgravois digging through some issues on this I think we might just be able to add https://github.com/mo/abortcontroller-polyfill/ to do cancelable requests. Basically:

1. Add `signal` to `requestOptions`.
2. Pass `signal` down to fetch.
3. If a user wants to enable cancelable requests in their application they should:
   1. Import their `Promise` and `fetch` polyfills
   2. Import `abortcontroller-polyfill` and patch fetch
   3. Follow https://developers.google.com/web/updates/2017/09/abortable-fetch as normal passing down a `signal` option to any `@esri/arcgis-rest-*` method.

Implementing `signal` is going to make it pretty tricky to use a custom `fetch` like we have right now since any custom `fetch` would also then have to implement `signal` and be cancelable but I think it is worth it.

**Comment by skitterm** [comment]
I would welcome having a timeout option for requests. It's helpful from a UX standpoint to control the amount of time waiting for a request, especially when the request is holding up other parts of a workflow.

**Comment by jgravois** [comment]
relevant (and from our friend @jamesmilneruk) https://www.loxodrome.io/post/cancelling-requests/

**Comment by jgravois** [comment]
this would still be cool if anyone wants to try and put together a PR, but I won't be tackling it anytime soon.
