### ISSUE TITLE
Geocoding - README links to old documentation

### ISSUE THREAD

**Issue by vicb** [Esri/arcgis-rest-js#1148]
### Describe the problem

The geocoding services ('geocode()` and `suggest()` functions) accept many more parameters than what is available in the current API.

For example there is no way to pass an initial location, a country code, nor the max number of results.

Ref: 

- [parameters for `geocode()`](https://developers.arcgis.com/rest/geocode/api-reference/geocoding-geocode-addresses.htm)
- [parameters for `suggest()`](https://developers.arcgis.com/rest/geocode/api-reference/geocoding-suggest.htm)
- [API parameters]()

### Describe the proposed solution

Add all missing parameters.

For `geocode` the existing interface (`interface IGeocodeOptions extends IEndpointOptions`) can be augmented with the additional parameters.

For `suggest` (`function suggest(partialText: string, requestOptions?: IEndpointOptions)`) there is a need to create a new interface `ISuggestOptions` extending `IEndpointOptions`

### Additional Information

I'm willing to create a PR if you are willing to accept it and release a new version with that.
Let me know!

**Comment by gavinr-maps** [comment]
Hi, thank you for logging this issue! 

> there is no way to pass an initial location, a country code, nor the max number of results

That is not strictly true. For all requests in ArcGIS REST JS, you can always use the `params` property to pass in any additional properties that is not covered within ArcGIS REST JS. See [IGeocodeOptions](https://developers.arcgis.com/arcgis-rest-js/api-reference/arcgis-rest-geocoding/IGeocodeOptions/):
![image](https://github.com/Esri/arcgis-rest-js/assets/137905994/68ae923d-7d15-4fd5-abae-73a2935ce7d2)


So although I don't think we are opposed to defining more of the REST API properties in ArcGIS REST JS, there _is_ a current way to pass anything you need to the REST endpoint.

**Comment by vicb** [comment]
@gavinr-maps Thanks for the tip!

I was looking at the doc referenced by the [README](https://github.com/Esri/arcgis-rest-js/tree/main/packages/arcgis-rest-geocoding) of the geocoding package.

That doc (https://esri.github.io/arcgis-rest-js/api/geocoding/geocode/) only mention the `address` parameters.

I see several options here:
- fix the link to the doc in your sceenshot
- update the doc at https://esri.github.io/arcgis-rest-js/api/geocoding/geocode/
- add more parameters (not exclusive)

Happy to help with any of those.
Let me know what you think

**Comment by gavinr-maps** [comment]
@vicb thanks for the response.

> I was looking at the doc referenced by the [README](https://github.com/Esri/arcgis-rest-js/tree/main/packages/arcgis-rest-geocoding) of the geocoding package.

Thank you for pointing that out - you're correct that those URLs are linking to our old v3 documentation (https://esri.github.io/arcgis-rest-js/api/) instead of the new v4 documentation (https://developers.arcgis.com/arcgis-rest-js/api-reference. If you would like to issue a PR to update that README, we would certainly appreciate that!

Note that the v4 documentation for geocoding is here: 
https://developers.arcgis.com/arcgis-rest-js/api-reference/arcgis-rest-geocoding/geocode/
... and on that page here is where the link to [IGeocodeOptions](https://developers.arcgis.com/arcgis-rest-js/api-reference/arcgis-rest-geocoding/IGeocodeOptions/) is:
![image](https://github.com/Esri/arcgis-rest-js/assets/137905994/1e1f7e63-597c-4085-82ee-27614ab07fc1)

Thank you!
