### ISSUE TITLE
changelog script throws fatal error when backticks are encountered in a commit message

### ISSUE THREAD

**Issue by jgravois** [Esri/arcgis-rest-js#123]
trying to tag `v1.0.3` i encountered the error below

```
$ node ./support/changelog.js
undefined:46
{"hash":"8d7f7ef4f4705738eddc5de74d92cc4f60462037","shortHash":"8d7f7ef","date":"2017-12-22T16:28:02-08:00","subject":"chore(commit-script): remove \`git add all\` from \`npm run c\`","author":{"name":"Patrick Arlt","email":"patrick.arlt@gmail.com"}},
                                                                                                                                                     ^

SyntaxError: Unexpected token ` in JSON at position 10854
    at JSON.parse (<anonymous>)
    at exec (/Users/john6251/github/arcgis-rest-js/support/changelog.js:77:28)
    at ChildProcess.exithandler (child_process.js:262:7)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at maybeClose (internal/child_process.js:927:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)

// offending line
const commits = JSON.parse(`[${stdout.slice(0, -1)}]`);

```

i'm scratching my head at how to debug this and genuinely afraid of wreaking unnecessary havoc by employing my usual method.

![changing stuff](https://pbs.twimg.com/media/Cf7eHZ1W4AEeZJA.jpg)

**Comment by patrickarlt** [comment]
@jgravois huh ill take a look likely something about https://github.com/Esri/arcgis-rest-js/blob/master/support/changelog.js#L77

**Comment by patrickarlt** [comment]
Turns out replacing escape characters is hard. All 3 of these options work on https://github.com/Esri/arcgis-rest-js/blob/master/support/changelog.js#L77

1. <code>JSON.parse("["+stdout.slice(0, -1).replace(/\\/g, "\\\\")+"]")</code> - Note you have to escape each escape character in the second arg of `replace`.
2. <code>JSON.parse("[" + stdout.slice(0, -1).split('').map(s => s.charCodeAt(0)).map(c => (c === 92 ? &#x60;\\${String.fromCharCode(c)}&#x60; : String.fromCharCode(c))).join("") + ']');</code> - Looks awesome as a 1 liner. Dismantles the whole string converts it all the charcodes looks for 92 replaces it with <code>\\&#x60;</code> and put the whole thing back together.
3. <code>eval(&#x60;[${stdout.slice(0, -1)}]&#x60;)</code> - You shouldn't use `eval` but this is hilarious since out JSON string is also a value JavaScript program with the correct escape characters and everything you can just `eval` it to get what you want, opening up for hilarious XSS attacks with git commits.

**Comment by jgravois** [comment]
the wizard meant.
```js
JSON.parse("["+stdout.slice(0, -1).replace(/\\/g, "\\\\")+"]")
```

thank you!
