### ISSUE TITLE
run express app behind the corporate proxy

### ISSUE THREAD

**Issue by chakreshsahu** [Esri/arcgis-rest-js#173]
When i am trying to run demo express application behind the corporate web proxy and visit http://localhost:3000/authorize. It redirect to the browser to portal's authorization url. After entering the credentials, it is giving following error.

```
Example app listening on port 3000!
(node:9356) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): FetchError: request to https://www.arcgis.com/sharing/rest/oauth2/token failed, reason: connect ECONNREFUSED 34.202.52.231:443

(node:9356) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code. (node:9356) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): FetchError: request to https://www.arcgis.com/sharing/rest/oauth2/token failed, reason: connect ECONNREFUSED 52.71.97.50:443
```

But when i try to run application in without corporate web proxy environment. It is working fine. 

Please suggest a way to pass proxy url in request.

**Comment by dbouwman** [comment]
When running in node or the browser, arcgis-rest-js uses `fetch` behind the scenes to make requests. Any requests sent from a browser will use the browse's proxy settings. But for node, apparently we need to pass proxy information to `fetch` via the `agent` property of it's [options](https://github.com/bitinn/node-fetch#options). 

The recommendation also appears to be to use [http-proxy-agent](https://github.com/TooTallNate/node-http-proxy-agent)

So that's the lower level solution... how would this work with `arcgis-rest-js`? 

One of the reasons the API allows you to pass [IRequestOptions](https://esri.github.io/arcgis-rest-js/api/request/IRequestOptions/), or something that extends that interface into *almost* every method, is that `IRequestOptions` allows you to pass in options that will be used by `fetch`. For example [getItem](https://esri.github.io/arcgis-rest-js/api/items/getItem/) 

For those methods, you should be able to construct an agent, and pass it as a property in the `IRequestOptions` hash.

However, after digging into this, it looks like the authentication related functions do not use this pattern. 

Perhaps @patrickarlt or @jgravois can shed some more light on how we can make this work? 

Can/should we add a `options` param on the methods in `UserSession` and `ApplicationSession` to allow an `agent` to be passed forward down the chain to the `fetch` call in `arcgis-rest-request`?

**Comment by vajnorcan** [comment]
Same question here

**Comment by tomwayson** [comment]
Something like this?

```js
const myAgent = {}; // TODO: set up agent

// create a function that wraps fetch() and adds the agent option
function fetchWithAgent(url, options) {

  const opts = Object.assign({}, options, { agent: myAgent });
  return fetch(url, opts);
}

// now call rest-js fns and pass in your custom fetch
getItem(id, { fetch: fetchWithAgent } );
```

**Comment by patrickarlt** [comment]
This probably relates to https://github.com/Esri/arcgis-rest-js/issues/880. We should consolidate all fetch options into `IRequestOptions.fetchOptions` and just pass everything down.

For the sessions yes we probally should figure out a way to do this which will likely be a mess.

**Comment by patrickarlt** [comment]
Our intent in the future is to migrate to the native version of fetch in Node. At v4 of ArcGIS REST JS (currently on the `beta` branch) we are removing support for custom `fetch` implementations. Ideally we would resolve this fully when the Node community figures out how to proxy native `fetch` in Node and we would follow those guidelines but for now this is extremely difficult to test and implement.
