### ISSUE TITLE
v1.2.0 Broke Semver: UMD output file names changed

### ISSUE THREAD

**Issue by dbouwman** [Esri/arcgis-rest-js#198]
It seems that the umd package naming changed, perhaps at the 1.2 release, and given how the libraray can be used, that should incur a major version bump.

Additionally, the `arcgis-rest-request` and  `arcgis-rest-feature-service` packages still include the OLD umd files

![image](https://user-images.githubusercontent.com/119129/40082104-39d3dee8-584d-11e8-9924-8d46954f3358.png)

I recommend we re-publish, without the old files, an with a 2.0.0 version number.

**Comment by dbouwman** [comment]
Update: we should yank the 1.2.0 release as well

**Comment by jgravois** [comment]
that was my fault. after i tidied up for the release i accidentally ran a build on an old branch and forgot to clear the output before i published to npm.

i'm fine with publishing v2.0.0, but my preference would be to tackle a few of the other breaking changes i listed in #137 before we do, mostly because none of them warrant a breaking change release of their own.

**Comment by tomwayson** [comment]
FYI - I've [deprecated](https://docs.npmjs.com/cli/deprecate) the 1.2.0 packages.
