### ISSUE TITLE
is beginOauth2 defaulting to the wrong portal?

### ISSUE THREAD

**Issue by tomwayson** [Esri/arcgis-rest-js#223]
The docs say [the portal will default to https://www.arcgis.com/sharing/rest](https://esri.github.io/arcgis-rest-js/api/auth/IOauth2Options/#portal), 

However, [`beginOAuth2()` actually defaults to https://arcgis.com/sharing/rest](https://github.com/Esri/arcgis-rest-js/blob/0878793cf3d2cdd05f7cdc39ede9802a415f8f85/packages/arcgis-rest-auth/src/UserSession.ts#L311)

I found when I used the default of https://arcgis.com/sharing/rest and then tried to call `getItemData()` I would see a CORS error (on the left below), but if I explicitly passed in `portal: "https://www.arcgis.com/sharing/rest",` to `beginOAuth2()` I did not get a CORS error (on the right below):

<img width="1679" alt="image" src="https://user-images.githubusercontent.com/662944/41484509-fb21c87e-7091-11e8-9ed8-50ca4bd93999.png">

Was defaulting to https://arcgis.com/sharing/rest just a mistake, or did we have some reason for that? It looks like JSAPI defaults to www: https://developers.arcgis.com/javascript/latest/api-reference/esri-portal-Portal.html#restUrl

**Comment by patrickarlt** [comment]
@tomwayson I think so. I think we should probably change this to https://www.arcgis.com/sharing/rest ASAP.

**Comment by jgravois** [comment]
someone told me ages ago that we should always direct folks exclusively to the `www` variant of ArcGIS Online uri because somehow it provided the better performance (perhaps because of load balancing?).

that said, to my devops-foo lackin ears, the fact that omitting it results in a CORS error sounds like NGINX is misconfigured such that the relevant response headers aren't passed along in the redirect.

**Comment by patrickarlt** [comment]
@jgravois I remembered where we ran into this in the Developers site. The `www` version is the only official documented and supported API. the non-`www` version is an old alpha/beta API that isn't supported but is kept around because apparently some legacy customer things still use it. There are some subtle differences between the 2 APIs like `created` vs `uploaded` for item creation dates.

In general though we should always use the `www` version of the API.
