### ISSUE TITLE
i meet https error? use portal bind Self-signed certificate?

### ISSUE THREAD

**Issue by liujunyi** [Esri/arcgis-rest-js#289]
error:
 FetchError: request to https://[server]/portal/sharing/rest/search failed, reason: unable to verify the first certificate

I had try cas,but it not work
require('ssl-root-cas').inject();
var rootCas = require('ssl-root-cas/latest').create();
rootCas
    .addFile(__dirname + '/ssl/pem.pem')
;
require('https').globalAgent.options.ca = rootCas;

**Comment by jgravois** [comment]
do you encounter an error/warning when you attempt to visit the portal using 'https' in the browser?

**Comment by liujunyi** [comment]
i used Self-signed certificate to my arcgis portal, I had solve it by change code,
i change @esri/arcgis-rest-request  code,change requese.js    
fetchOptions = {
            method: httpMethod,
            // ensures behavior mimics XMLHttpRequest. needed to support sending IWA cookies
          ++++  agent:new https.Agent({rejectUnauthorized: false}),
            credentials: "same-origin"
        };

**Comment by jgravois** [comment]
nice work.

**Comment by b00tsy** [comment]
I'm facing the same problem here with 4.x but the proposed solution seems to require overriding request.js, which kind of is making using the whole library obsolete.

From comments around other issues (unfortunately browsed thru too many and closed them already) I saw a comment on an issue that you're planning to allow passing fetch options from the calling method. Is that already a thing?

That's the context I need to deal with that.
```
const { queryFeatures } = require('@esri/arcgis-rest-feature-service')
const features = await queryFeatures({
  fetchOptions: { https: { rejectUnauthorized: true } }
})
```

Of course better would be to be able to define the expected `ca` instead of ignoring the tls validation, which I'd assume to be able to configure in such a way.

Currently I'm using raw node http libraries, where I can customize such things directly, using arcgis rest js, however, would make everything more convenient...
