### ISSUE TITLE
Empty Postal Code with findAddressCandidates...

### ISSUE THREAD

**Issue by maximelebreton** [Esri/arcgis-rest-js#370]
Hi there,

I try to use the `findAddressCandidates` api, and everything is working except the postal code, who is empty (on all cities I've tested).

**My request:**
https://geocode.arcgis.com/arcgis/rest/services/World/GeocodeServer/findAddressCandidates?f=json&city=Paris&outFields=City,Postal&maxLocations=10&sourceCountry=FRA

**The returned `json`**
```javascript
[
//...
{
  // ...
  City: "Paris"
  Postal: "" // <- No postal code...
  // ...
}
//...
]
```

Is it a bug, or I missed something?

Thank you!

**Comment by maximelebreton** [comment]
And if I search a french Postal Code, like `56800`, who is related to 9 cities :

```javascript
axios.get('https://geocode.arcgis.com/arcgis/rest/services/World/GeocodeServer/findAddressCandidates', {
          params: {
            f: "json",
            postal: '56800',
            outFields: "*",
            sourceCountry: "FRA",
            maxLocations: 5
          }
        })
```

I have only one result, instead of 9...
```javascript
[{
  //...
  City: "Campénéac"
  Postal: "56800"
  //...
}]
```

**Comment by jgravois** [comment]
its difficult to explain, but geocoding just doesn't work that way.

> everything is working except the postal code, who is empty (on all cities I've tested).

our geocoder compares your input parameters to a composite collection of data sources for discrete point match and the best match for `"Paris"` or any other city is a point feature representing the entire city. that feature does not include a postal attribute because it represents a larger geography that spans many postal zones.

to put it another way, just because you ask for a particular output field doesn't guarantee that it is present in the feature that the geocoder determines the best match for our input parameters.

> And if I search a french Postal Code, like 56800, who is related to 9 cities...

our geocoder is attempting to return a single match, not a comprehensive collection of all features that share an attribute. when you set `maxLocations`, this isn't intended to provide you with **a more comprehensive collection**, it only helps in cases where the geocoder isn't sure what the best match is and returns more candidates so that you can evaluate them on your own.

my guess is that the _centroid_ of postal code `56800` is in the city of Campénéac.

i'm happy to chat about this more if it'd be helpful.

**Comment by maximelebreton** [comment]
Thank you for the explanation @jgravois!

But is it possible to make it work in my way with any ArcGIS API, or should I migrate to an other API, like OSM, Google Maps or Mapbox?

Greetings

**Comment by jgravois** [comment]
i'm no expert, but i don't think OSM, Google Maps or Mapbox's geocoders work the way you're hoping either.

> But is it possible to make it work in my way with any ArcGIS API

if you want to know what postal codes share geographic boundaries with cities in France, you just need to either identify existing public spatial services for both or spin up two new ones of your own.

https://developers.arcgis.com/labs/rest/query-a-feature-layer/
https://developers.arcgis.com/labs/arcgisonline/import-data/

**Comment by mpayson** [comment]
hi @maximelebreton , another thought is you can take the location result from `findAddressCandidates` and pass it in to `reverseGeocode`

`findAddressCandidates` assumes you knows the addresses and optimizes fetching coordinates, and `reverseGeocode` assumes you know the coordinates and optimizes fetching address information, so the latter returns more address-type data

for example, the first candidate from your [request](https://geocode.arcgis.com/arcgis/rest/services/World/GeocodeServer/findAddressCandidates?f=json&city=Paris&outFields=City,Postal&maxLocations=10&sourceCountry=FRA) is
```
{
  address: "Paris, Île-de-France",
  location: {
    x: 2.3414000000000215,
    y: 48.85717000000005
  }...
}
```

if you pass this in to the `reverseGeocode` endpoint:
> http://geocode.arcgis.com/arcgis/rest/services/World/GeocodeServer/reverseGeocode?location=2.3414000000000215,48.85717000000005&f=json

then you get a bunch more metadata
```
{
  "address": {
    "Match_addr": "Pont Neuf, 75001, 1er Arrondissement, Paris, Île-de-France",
    "LongLabel": "Pont Neuf, 75001, 1er Arrondissement, Paris, Île-de-France, FRA",
    "ShortLabel": "Pont Neuf",
     ...
    "Subregion": "Paris",
    "Region": "Île-de-France",
    "Territory": "",
    "Postal": "75001",
    ....
  }....
}
```

**Comment by maximelebreton** [comment]
Many thanks to @jgravois and @mpayson,
it requires two calls, and I would rather like one call solution, but it's working!

**Comment by maximelebreton** [comment]
_The @mpayson message has disappeared (dont know why?), so I repast it here:_


> 
> hi @maximelebreton , another thought is you can take the location result from findAddressCandidates and pass it in to reverseGeocode
> 
> findAddressCandidates assumes you knows the addresses and optimizes fetching coordinates, and reverseGeocode assumes you know the coordinates and optimizes fetching address information, so the latter returns more address-type data
> 
> for example, the first candidate from your request is
> 
> ```
> {
>   address: "Paris, Île-de-France",
>   location: {
>     x: 2.3414000000000215,
>     y: 48.85717000000005
>   }...
> }
> ```
> if you pass this in to the reverseGeocode endpoint:
> 
> http://geocode.arcgis.com/arcgis/rest/services/World/GeocodeServer/reverseGeocode?location=2.3414000000000215,48.85717000000005&f=json
> 
> then you get a bunch more metadata
> 
> ```
> {
>   "address": {
>     "Match_addr": "Pont Neuf, 75001, 1er Arrondissement, Paris, Île-de-France",
>     "LongLabel": "Pont Neuf, 75001, 1er Arrondissement, Paris, Île-de-France, FRA",
>     "ShortLabel": "Pont Neuf",
>      ...
>     "Subregion": "Paris",
>     "Region": "Île-de-France",
>     "Territory": "",
>     "Postal": "75001",
>     ....
>   }....
> }
> ```

**Comment by patrickarlt** [comment]
@maximelebreton a little late on this but I thought I would comment since this might be helpful. 

If you are trying to do something like "Find all Zip Codes in the city of Paris" you might want to look at standard geography queries https://www.esri.com/arcgis-blog/products/arcgis-online/uncategorized/best-practices-how-to-query-standard-geographies-branches/ which are part of the Geoenrichment API.
