### ISSUE TITLE
How to assist consumers in formating query response values, i.e. based on popupInfo?

### ISSUE THREAD

**Issue by tomwayson** [Esri/arcgis-rest-js#393]
This recently came up in https://github.com/Esri/arcgis-rest-js/pull/386#discussion_r232855938, if we're processing fields to decode coded value domains should we also provide a way for consumers to format date and numeric fields?

There has also been interest in potentially using the [format](https://developers.arcgis.com/web-map-specification/objects/format/) info from [fieldInfo](https://developers.arcgis.com/web-map-specification/objects/fieldInfo/) objects in a layer's [popupInfo](https://developers.arcgis.com/web-map-specification/objects/popupInfo/) to format attribute data.

Seems like if we wanted to take this on our choices are:
- use the built-in `toLocaleString()` fns (now we need to know the locale and deal w/ potential browser/node idiosyncrasies)
- let consumers provide a callback where they can use whatever formatting library they have (how much are we even helping at that point?)
- ~take on another library as a dependency~

The latter isn't really even an option considering that even the _smallest_ date formatting library out there, [dateformat](https://bundlephobia.com/result?p=dateformat@3.0.3), is ~1.5x the size of the entire @esri/arcgis-rest-feature-service package. The depressingly popular [moment.js is about 64x as large](https://bundlephobia.com/result?p=moment@2.22.2)!!!

Maybe one thing we could do as a start that could be useful is to provide a fn that translates the ArcGIS date format types to patterns like `MM/dd/yyyy` that can could then be used w/ popular date libraries like moment. See [these examples](https://developers.arcgis.com/net/latest/ios/api-reference/html/T_Esri_ArcGISRuntime_Mapping_Popups_PopupDateFormat.htm). That would depend on the date libraries using the same or at least very similar patterns.

**Comment by jgravois** [comment]
i played around a little today and noticed that in the JSAPI, when a layer is instantiated from a portal item, its popupInfo doesn't impact what is returned by 'queryFeatures()'.

instead, the attributes associated with a particular feature are massaged after the fact (just in time to display a popup).

because of this, i _guess_ it makes sense to follow the pattern we established in #386 

```ts
queryFeatures(/* */)
  .then(queryResponse => {
    formatValues({
      queryResponse,
      // use the item id to fetch fieldInfos if they aren't provided directly
      fieldInfos: itemId as string | fieldInfo[]
    })
      .then(formattedResponse)
  })
```
where to put the utility function though? `items` doesn't make a whole lot of sense, but given what we'll need to call internally, neither does `feature-service`.

either way, more information about the proposed use case would be helpful.
