### ISSUE TITLE
Question: load kml files upto 80 megbytes total(10 megabytes per file)

### ISSUE THREAD

**Issue by ronen5353** [Esri/arcgis-rest-js#410]
Hi I am using Arcgis for JS version 4.9, I am trying to load upto 8 kml files(each file is about 10 megabytes).
The loading of the kml is passing successfully but the interaction(pan&zoom) with the map is very slow and not smooth. 
I have several questions regarding this issue:
1. Can Esri load such an amount of kml files? if not is there any other alternatives ?
2. Why in openlayers I can do it smoothly and in pure arcgis it more problematic?
3. Can I upload a RAW kml data and not diretly via hosting url?

I would appreciate any kind of help, thanks in advance!!

**Comment by jgravois** [comment]
hi @ronen5353 

> disclaimer: i don't represent the ArcGIS API for JavaScript team and this repository is used to discuss an entirely different codebase. 

that said, i don't expect that the ArcGIS API for JavaScript will _ever_ attempt to optimize the display of nearly 100MB of kml in the browser.

as a company, we are working hard to push the boundaries of performance via many different technologies and features:

* WebGL
* vector tiles
* client-side [queries](https://www.esri.com/arcgis-blog/products/js-api-arcgis/mapping/turbo-charge-your-web-apps-with-client-side-queries/) and spatial analysis
* [quantization](https://www.esri.com/arcgis-blog/products/arcgis-enterprise/announcements/whats-new-with-feature-services-in-10-6/)
* [web assembly](https://www.esri.com/arcgis-blog/products/js-api-arcgis/mapping/introducing-the-client-side-projection-engine/) 
* etc.

but this work is centered around communication with spatial web services because this approach is much more nimble and scalable than downloading every conceivable feature that you'd ever possibly want to see from a series of flat files.

cc/ @andygup @bsvensson

**Comment by andygup** [comment]
@ronen5353 thanks for reaching out. Do you have a sample app you can share? If you don't want it public you can email it to me: agup at esri dot com.
