### ISSUE TITLE
make sure all fns that wrap `request()` don't break w/ `rawResponse: true`

### ISSUE THREAD

**Issue by tomwayson** [Esri/arcgis-rest-js#462]
Example:

https://github.com/Esri/arcgis-rest-js/blob/9ee647b419bce13de85dce2ca4d109c149e82ee5/packages/arcgis-rest-feature-service/src/query.ts#L140

**Comment by thw0rted** [comment]
Hi @tomwayson , it looks like this didn't update the return types for calling functions, so they're not correct under `rawResponse: true`.  For example, [queryFeatures](https://esri.github.io/arcgis-rest-js/api/feature-layer/queryFeatures/) still thinks it always returns  `Promise<IQueryFeaturesResponse | IQueryResponse>`.  Should I open a new issue to have these functions return `Promise<Response>` when `rawResponse` is true?

**Comment by tomwayson** [comment]
thanks @thw0rted - so you're suggesting opening an issue to track all the fns whose return types need to be updated w/  `| Promise<Response>`?

**Comment by thw0rted** [comment]
Yes Tom, that's the idea. I only use the feature-layer API, so I'm not familiar with the layout of the rest of the ecosystem.  Would this still be the right place for an issue like that?  Is there any reason not to add that return type?

Also, instead of `|Promise<Response>`, would it be possible to use overloading akin to

````ts
function queryFeatures({
  ...
  rawResponse: true,
  ...
}): Promise<Response>
function queryFeatures({
  ...
  countOnly: true,
  rawResponse?: false,
  ...
}): Promise<IQueryResponse>
function queryFeatures({
  ...
  countOnly: false,
  rawResponse?: false,
  ...
}): Promise<IQueryFeaturesResponse>
````

I think that would get complex quickly because there are several "only" flags that can change which response type you get (IDs, count, extent?).  You might be able to use an a union type to simplify a bit, but I haven't tried myself.  Then again, Angular's HTTPClient class has a straightforward list of overloads for all the methods -- the typings alone run to over 3000 lines.  Maybe they went that way because it's easier to read / maintain?  Anyway, would be nice to have, but not a huge deal.

**Comment by thw0rted** [comment]
I came here from #702 -- I use `queryFeatures` and haven't needed `rawResponse` yet.  Now that there's a PBF spec / helper available, I plan to try implementing it, and I was hoping to use the fetch ReadableStream so I could pull Messages as they come over the wire.  From what I can tell, it would be a build error to try to use the return value from `queryFeatures` directly given its type definitions today. You'd have to double-cast e.g. `const resp = (await (queryFeatures({..., rawResponse: true})) as any as Response;`.
