### ISSUE TITLE
Params with a "null" value are not included in request.

### ISSUE THREAD

**Issue by ssylvia** [Esri/arcgis-rest-js#495]
I'm using the `updateItem` method to set the `itemDetails` and `itemData` on a Story Map. If a user clicks "Unpublish", we need to remove this `itemData`. This should be able to be accomplished with the following:

```ts
updateItem({
  authentication: this.userSession,
  item: this.itemDetails,
  params: {
    // Clear item data
    text: null,
  },
})
```

However, the `text: null` is never included as a param in the request.

Currently, I have to make a second request if I want to update the itemDetails and remove the itemData at the same time:

```ts
addItemJsonData({
  authentication: this.userSession,
  id: this.itemId,
  data: null,
});
```

**Comment by jgravois** [comment]
right now to send a parameter with an empty key you need to pass `""`.

https://github.com/Esri/arcgis-rest-js/blob/master/packages/arcgis-rest-request/src/utils/process-params.ts#L62-L65

would that work for you in this scenario?

**Comment by jgravois** [comment]
i did a little testing and i was _not_ able to reproduce the behavior you described.

for me, this syntax induces the error below.
```js
addItemJsonData({
  authentication,
  id,
  data: null,
});
```

> {"error":{"code":400,"messageCode":"CONT_0057","message":"Invalid JSON in 'text' parameter.","details":[]}}

i just opened #496 with a tweak that resolves the error, but does _not_ get to the root of your problem.

when those changes are incorporated:

1. `data: null` causes the parameter to be dropped entirely (which is consistent with the rest of the library).
2. `data: ""` causes an empty param _is_ passed, which i assume is what you want. Unfortunately, the Portal API appears to ignore it (even if you send the additional parameter below).

```js
addItemJsonData({
  authentication,
  id,
  data: "",
  params: { clearEmptyFields: "text,data" } 
});
```

because of the hair pulling i did in #474, i can safely say that `clearEmptyFields` is only honored by string fields. you can pass a `","` to clear `tags` but i don't know of another way to clear item `data` (other than passing `{}`).

**Comment by ssylvia** [comment]
Thanks @jgravois. I was originally testing by looking at the output in AGO Assistant. With further investigation on my end, it looks like passing `null` is not what I want as you suspected. I reached out to few members of the Portal API team and they were unaware of a method to actually clear the itemData once it's been added. 

The empty text string is probably what we want. I'll submit an issue with the Portal API team to get this added. I'll close this issue for now.

**Comment by jgravois** [comment]
> I was originally testing by looking at the output in AGO Assistant. 

i feel you there. i've been tricked doing that too.
