### ISSUE TITLE
SearchQueryBuilder should support .not as the start of the query

### ISSUE THREAD

**Issue by pranavkulkarni** [Esri/arcgis-rest-js#542]
AGO support queries like `"-access:public" AND "-type:code attachment"`. 

Currently, if I try this 
```
let query = new SearchQueryBuilder();
  query
  .not()
  .match('public')
  .in('access')
  .not()
  .match('code attachment')
  .in('type')
```

it fails `You have called `not()` without calling another method to modify your query first. Try calling `match()` first.`

It would nice to support a syntax like 
```
let query = new SearchQueryBuilder();
  query
  .not()
  .match('public')
  .in('access')
  .and()
  .not()
  .match('code attachment')
  .in('type')
```

**Comment by jgravois** [comment]
the full AGO query you want to be able to compose is this?

```
NOT (-access:public AND -type:"code attachment")
```

**Comment by jgravois** [comment]
if you snoop the web traffic in ArcGIS Online when a search like ^^ is made, you can see that additional parameters are appended internally to ensure that the search is not entirely composed of negatives.

<img width="1165" alt="Screen Shot 2019-04-23 at 10 11 05 AM" src="https://user-images.githubusercontent.com/3011734/56601510-320ef000-65b0-11e9-97ca-a4db0f9e0193.png">

this makes me feel like our current restriction on the use of modifiers on empty queries is a good one.

```ts
let q = new arcgisRest.SearchQueryBuilder();
q
  .match(`${orgid}`)
  .in('orgid')
  .not()
  .match('public')
  .in('access')
  .not()
  .match('code attachment')
  .in('type')
```

**Comment by patrickarlt** [comment]
@pranavkulkarni I built a quick scratch app and all of these queries are idential

```text
test AND owner: patrickarlt7104 NOT access: public
93 results
test AND owner: patrickarlt7104 AND -access: public
93 results
test AND owner: patrickarlt7104 AND NOT access: public
93 results
test AND owner: patrickarlt7104 AND -access: public
93 results
```

You can see the full test app at https://gist.github.com/patrickarlt/8d350e181f212b2698dec824f6da103e.

I think we do need to loosen up the usage of `.not()` since it is different then `.and()` and `.or()` so:

1. `.not()` should be allowed at the start of a query, this allows for things like

    ```js
    var q = new SearchQueryBuilder()
      .not()
      .match("public")
      .in("access");
    ```

   currently this is possible anyway with so we should allow it with `.not()`

    ```js
    var q = new SearchQueryBuilder()
      .match("public")
      .in("-access");
    ```
2. We should allow `.not()` after other modifiers this would allow the following 2 queries which produce identical results:

    ```js
    var q = new SearchQueryBuilder()
      .match("test")
      .and()
      .match("patrickarlt7104")
      .in("owner")
      .not()
      .match("public")
      .in("access")
      .not()
      .match("code attachment")
      .in("type");

    var q = new SearchQueryBuilder()
      .match("test")
      .and()
      .match("patrickarlt7104")
      .in("owner")
      .not()
      .match("public")
      .in("access")
      .and() // no reason to not allow this
      .not()
      .match("code attachment")
      .in("type");
    ```

@pranavkulkarni with these in place

````
let query = new SearchQueryBuilder();
  .not()
  .match('public')
  .in('access')
  .not()
  .match('code attachment')
  .in('type')
```

should produce `NOT access:public NOT type:"code attachment"` which is equivalent to `
`-access:public AND "-type:"code attachment`. If you want this  to produce EXACTLY `-access:public AND "-type:"code attachment` you'll need to do:

```js
let query = new SearchQueryBuilder();
  .match('public')
  .in('-access')
  .and()
  .match('code attachment')
  .in('-type')
```

We should probably document the use of `-` as an equivalent to `.not()` that you can pass to `match()` or `in()`.

**Comment by jgravois** [comment]
i tackled this in #545.
