### ISSUE TITLE
OAuth popup always requests permission.

### ISSUE THREAD

**Issue by COV-GIS** [Esri/arcgis-rest-js#554]
This might be more related to portal than this api. The popup requests permission every time a user signs in and is already signed into portal or another app. Which seems odd. I'm converting some apps from azure active directory oauth. AAD asks the first time and all subsequent times the popup opens to auth and then immediately closes if signed in elsewhere. Most times so fast you don't even see it.

Is this the expected behavior? Shouldn't portal know the user already approved? Or is there a method to bypass this behavior via the app auth process?

**Comment by jgravois** [comment]
> is there a method to bypass this behavior via the app auth process?

its up to you to persist a user's session if you don't want them to 'stay' logged in.

https://github.com/Esri/arcgis-rest-js/blob/3fefa68d195595e90247c047bb51570716828cd4/demos/oauth2-browser/authenticate.html#L22-L25

https://github.com/Esri/arcgis-rest-js/blob/3fefa68d195595e90247c047bb51570716828cd4/demos/oauth2-browser/index.html#L95-L102

**Comment by COV-GIS** [comment]
Unrelated to persisting the user session. I mean when the user is signed into portal and needs to sign into the app and has already clicked the APPROVE button before from a previous sign in. Why is portal asking for permission again?

For example if I've given an AAD registered app permission the first time I signed into it at work, go to a computer I've never used before, sign into outlook, and then click the sign in button in the app, popup opens/closes, redirect and I'm signed in.

Portal must need permission every time.

**Comment by jgravois** [comment]
If i'm understanding correctly, the behavior you describe isn't peculiar to enterprise portals.

If you:

1. register an application with ArcGIS Online
2. sign into www.arcgis.com
3. launch OAuth from the custom application

you'll encounter the dialog below.

<img width="498" alt="Screen Shot 2019-04-26 at 9 59 21 AM" src="https://user-images.githubusercontent.com/3011734/56823912-02f3bb00-680a-11e9-8571-27c5adb11783.png">

Even on the same machine, if the session isn't persisted manually, the next time you launch the app, the same dialog will be displayed.

I've never really thought about it before, but it'd obviously be preferable if the www.arcgis.com session was interpreted seamlessly the second time around.

i could be missing something, but this is likely because we don't surface an option anywhere for users to revert approval they've given for applications to act on their behalf.
