### ISSUE TITLE
Cannot `request` a public layer

### ISSUE THREAD

**Issue by jpeterson** [Esri/arcgis-rest-js#559]
I'm on v2.0.0

I'm running into an [`ArcGISAuthError`](https://esri.github.io/arcgis-rest-js/api/request/ArcGISAuthError/) when trying to request [a public MapServer layer](https://sampleserver6.arcgisonline.com/arcgis/rest/services/USA/MapServer/2).

```js
request('https://sampleserver6.arcgisonline.com/arcgis/rest/services/USA/MapServer/2',
  {
    httpMethod: 'GET',
    authentication
  }
);
```

My [UserSession's `portal` property](https://esri.github.io/arcgis-rest-js/api/auth/UserSession/#portal): `https://qaext.arcgis.com/sharing/rest`.

Result:

![image](https://user-images.githubusercontent.com/3399064/56981557-64829500-6b3c-11e9-9f6d-49cafa385f39.png)

```json
{
  "name": "ArcGISAuthError",
  "message": "NOT_FEDERATED: https://sampleserver6.arcgisonline.com/arcgis/rest/services/USA/MapServer/2 is not federated with any portal and is not explicitly trusted.",
  "originalMessage": "https://sampleserver6.arcgisonline.com/arcgis/rest/services/USA/MapServer/2 is not federated with any portal and is not explicitly trusted.",
  "code": "NOT_FEDERATED",
  "url": "https://sampleserver6.arcgisonline.com/arcgis/rest/services/USA/MapServer/2",
  "options": {
    "httpMethod": "GET",
    "params": {
      "f": "json"
    },
    "authentication": {
      "clientId": "KU6w5ji2TfnAx5gl",
      "username": "jpeterson_iot",
      "token": "U_HrpG0BBRwPxk17JENdPIvIvooLNGyJez-vYEPiw-w2cpedH9EvAtk1cFbZF-zdp1j2KrVxF23KmGvztgpDtPYuXvvRA1uXmHcIDGaHe9yT8uZqnsEYE6Q9GlCPwN9X5EAkkPZLc8mGv9iH8hiV96Z1863QPqX4JCMbQy9I8Q6m4GF8VH0mPXMxNKO37PzR1wRxCu-cc72Fbg8-g3KzFZ2QejrAFhNja6TfUheG_jk.",
      "tokenExpires": "2019-05-14T16:30:40.047Z",
      "portal": "https://qaext.arcgis.com/sharing/rest",
      "ssl": true,
      "tokenDuration": 20160,
      "refreshTokenTTL": 1440
    },
    "headers": {}
  }
}
```

Maybe related?
https://github.com/Esri/arcgis-rest-js/issues/242
https://github.com/Esri/arcgis-rest-js/pull/245#pullrequestreview-137613161

**Comment by jgravois** [comment]
its by design that ArcGIS REST JS attempts to authenticate and append a valid token to a request any time a session is provided.

in this case, since `sampleserver6` isn't federated with `qaext.arcgis.com`, REST JS aborts as soon as it learns it won't be able to generate a valid token. this is because we don't know in advance whether the endpoint is public or private.

if you have a reference to a UserSession and you're making calls to unfederated, public services too, one option you have is to `catch` the AuthError and retry _without_ authentication.

```ts
request(url, { authentication })
  .catch(err => {
    if (err.name === 'ArcGISAuthError') {
      // instead of supplying authentication, strip it 
      err.retry(() => Promise.resolve(undefined))
        .then(response)
    }
  })
```

this feature was added in https://github.com/Esri/arcgis-rest-js/pull/503

**Comment by jpeterson** [comment]
Thanks @jgravois! Works for me.

**Comment by jgravois** [comment]
glad to hear it.

i'll be thinking about how/where we could make this clearer in the documentation. if you have any suggestions, _please_ don't be shy.

**Comment by jpeterson** [comment]
Yeah, feels like a hard one to doc, but I don't think this is really an edge case that an authenticated user would want to fetch a random public service.

I guess I would have discovered this by looking in these places (in order):

1. A note on the [ArcGISAuthError doc page](https://esri.github.io/arcgis-rest-js/api/request/ArcGISAuthError/) with a code snippet.

2. [A comment here](https://github.com/Esri/arcgis-rest-js/blob/4576dc3ad28037f6e0e7e6fec17883d5d90c0a85/packages/arcgis-rest-auth/src/UserSession.ts#L820) describing this scenario.

#### Long explanation of our use case:
In [Analytics for IoT](https://www.esri.com/en-us/landing-page/product/2018/arcgis-analytics-for-iot), we are building an "Item Browser" whereby a user can discover items in ArcGIS Online with a similar experience to the "Content" page in Online. Whenever the user selects an item, we interrogate the item and fetch pertinent details to display for our user.

Scenario relevant to this issue: a user has an item created by "Add Item" > "From the web" (on the Content page), which results in an item that has a `url` property pointing to wherever the service lives.

**Comment by patrickarlt** [comment]
@jgravois I'm reopening this because it is coming up more and more.

If I make a request to an unfederated server I think we should do the following:

1. A `request` is made to an unfederated server `sampleserver6` with `UserSession`
2. `UserSession` figures out that `sampleserver6` isn't federated with `arcgis.com` so we know our `UserSession` won't work.
3. Try the `request` without a token at all since we know the token we have won't work.
4. If the `request` succeeds great. We are done.
5. If the `request` fails with an auth error we can throw the not federated error

**Comment by jgravois** [comment]
@jpeterson, just in case you didn't already see it...

as of [`v2.0.1`](https://github.com/Esri/arcgis-rest-js/releases/tag/v2.0.1) requests to public, unfederated services with a valid ArcGIS Online or Portal UserSession appended should "just work".

**Comment by jpeterson** [comment]
@jgravois I did see – excellent work! I think this is a great improvement to the library.
