### ISSUE TITLE
Using with non-federated (standalone) servers not associated to portal

### ISSUE THREAD

**Issue by roemhildtg** [Esri/arcgis-rest-js#604]
Is it possible to use this library with standalone servers for making basic rest requests against a standalone arcgis server? Meaning not federated or trusted by any portals, I just want to generate an arcgis server token and make requests against the endpoints. 

I'm running into errors thrown in this library that say the server cannot be trusted since its not a federated server...etc I am hoping someone here may know more about this.

**Comment by patrickarlt** [comment]
You should be able to follow the flow of this here https://github.com/Esri/arcgis-rest-js/blob/master/packages/arcgis-rest-auth/src/UserSession.ts#L825-L900. But if you don't want to parse the code here is what we are doing:

1. We make a request to the servers `/rest/info` endpoint
2. We check for `response.owningSystemUrl` to see if the server is federated with a portal
3. If there is no `response.owningSystemUrl` we check for `response.authInfo` and use it to generate the token  
4. If both 2 and 3 are false (no `owningSystemUrl` or `authInfo`) we can't automate authentication because the server doesn't advetise a portal or token endpoint.

I'm going to guess that you just have a configuration of server that we haven't encountered before. Could you do the following to help us debug:

1. Post the contents of your servers `rest/info` endpoint here https://developers.arcgis.com/rest/services-reference/server-info.htm.
2. Provide some sample code as to how you are using this? You can obscure URLs/usernames/passwords but it would be helpful to debug this.

**Comment by jgravois** [comment]
see https://github.com/Esri/arcgis-rest-js/pull/423

**Comment by COV-GIS** [comment]
You can use [generateToken()](https://esri.github.io/arcgis-rest-js/api/auth/generateToken/) directly against the server token endpoint using a built-in server user where the the token url is something like `https://<server>/arcgis/tokens/generateToken`. Or just use [request()](https://esri.github.io/arcgis-rest-js/api/request/request/) with the url and appropriate [generateToken](https://developers.arcgis.com/rest/services-reference/generate-token.htm) params. Then include the `token` with your other requests.

**Comment by roemhildtg** [comment]
Thanks for all the info guys. I have the method that @COV-GIS  mentioned working. I'm going to investigate further to see why I was encountering the error. I'll follow up with more details shortly

**Comment by roemhildtg** [comment]
@patrickarlt here's my json. I don't believe there's anything special about this, I was probably just incorrectly using the library.

```json
{
  "currentVersion": 10.71,
  "fullVersion": "10.7.1",
  "soapUrl": "https://services.wsbeng.com/arcgis/services",
  "secureSoapUrl": null,
  "authInfo": {
    "isTokenBasedSecurity": true,
    "tokenServicesUrl": "https://services.wsbeng.com/arcgis/tokens/",
    "shortLivedTokenValidity": 480
  }
}
```

**Comment by roemhildtg** [comment]
Okay - here's what I'm doing to get that error:

```javascript
    const authentication = new UserSession({
        server: arcgis.url,
        username: arcgis.username,
        password: arcgis.password,
        tokenDuration: arcgis.tokenExpires,
    });

    const defaultParams = { ...DEFAULT_PARAMS };
    console.log(defaultParams);

    const layerProps = config.featureLayer;
    const layerUrl = `${layerProps.url}/FeatureServer/${layerProps.layerId}`;
    await authentication.getToken(layerUrl);
```

This throws `'NOT_FEDERATED: https://services.wsbeng.com/arcgis/rest/services/wsb/projects/FeatureServer/4 is not federated with any portal and is not explicitly trusted.'`

**Comment by jgravois** [comment]
> // I think we need to do this in order to use the authentication in requests?
> await authentication.getToken(layerUrl);

that isn't necessary. anytime you pass `authentication` in a normal request, we will fetch a token and cache it.

what is `arcgis.url` in your code snippet?

```

**Comment by roemhildtg** [comment]
Its just the arcgis server root: `https://services.wsbeng.com/arcgis/`.

**Comment by roemhildtg** [comment]
Funny I got it working. I just removed the last slash. I'm dumb and can't follow the docs. I just looked over them again and saw that you guys don't pass the last slash and that's what did it for me. 

Thanks for the troubleshooting guys!

**Comment by jgravois** [comment]
not your fault.

https://github.com/Esri/arcgis-rest-js/blob/0768eab390912591e0aadbfbed114a306d991a01/packages/arcgis-rest-auth/src/UserSession.ts#L790

should be:
```ts
const [root] = cleanUrl(url).split(/\/rest(\/admin)?\/services(?:\/|#|\?|$)/)
```
