### ISSUE TITLE
smart support for GET (which switches to POST automatically)?

### ISSUE THREAD

**Issue by jgravois** [Esri/arcgis-rest-js#66]
our current implementation of esriRequest defaults to POST and allows a GET to be issued manually.

@patrickarlt's preference is to recommend that packages default to POST and skip implementing logic to switch from a GET to a POST after the commonly accepted ~2000 character limit has been exceeded.

this issue is intended to track interest from other developers who would like to piggyback off a _smart_ request method instead of defaulting to POST (or implementing the logic above in their own package).

anecdotally, it didn't take me long to identify an ArcGIS Server operation that _appears_ to only support GET

* http://sampleserver6.arcgisonline.com/arcgis/rest/services/Census/MapServer/dynamicLayer
* http://resources.arcgis.com/en/help/arcgis-rest-api/index.html#/Dynamic_Layer_Table/02r3000000q0000000/

**Comment by tomwayson** [comment]
I just bumped into an issue where koop services don't support POST. Also, debugging the POST query to figure that out was not as easy as debugging a GET - not hard, just inconvenient.

I really think defaulting to POST is going to cause more problems than it's worth. I know _these libraries_ don't support non-CORs browsers, and I guess we won't officially support services that don't have CORs on or accept POST, _but_ these libraries will be used in applications that do have to support those scenarios. I worry that there will be dozens of consuming libraries that will have to implement the same < 2000 char limit logic, and it seems like that's better dealt w/ in a centralized place.

I'm still unsure if we should have `request()` do this, or have the individual libs handle it. I prefer the former. Whichever we decide, I'm willing to PR.

**Comment by tomwayson** [comment]
@patrickarlt do you agree that this should be settled before v1 release?

**Comment by jgravois** [comment]
personally, i'm okay with shipping a v1 that defaults to `POST` and allows devs to `GET` or incorporate their own logic to switch between the two.

with something 'smart' i assumed we'd be aiming for (another?) wrapper to switch between the two for them automagically so i don't envision it being a breaking change.

**Comment by tomwayson** [comment]
So after some back and forth, w/ @jgravois, it seems the [2k limit might be on the server side](https://stackoverflow.com/questions/15090220/maximum-length-for-url-in-chrome-browser). Looking at https://github.com/Esri/cedar/pull/346, the service in question is a hosted feature service.

I think the hassle of debugging POST requests and the awkward HTTP verb semantics of POSTing for queries, and warrant defaulting to GET for those requests.

However, after realizing that the char limit is an AGO thing, possibly only scoped to hosted feature services, I now lean towards it being the responsibility of the individual libraries to use GET appropriately, the way that @dbouwman did [for the search/get operations for arcgis-rest-items](https://github.com/Esri/arcgis-rest-js/blob/b052733184f4b6b74c6db82c473dad7aa2b6cc74/packages/arcgis-rest-items/src/items.ts#L53). So, we know the char limit is a thing for hosted feature services, so arcgis-rest-feature-service should deal w/ it in it's `query()`. If it turns out there's also a similar limit for item searches, then we'll abstract the logic out so that it can be used by arcgis-rest-items too.

B/c arcgis-rest-items is doing the right thing (so far as we know) and b/c we haven't implemented arcgis-rest-feature-service yet, I don't think we'll be making any breaking changes if we follow this strategy.

**Comment by patrickarlt** [comment]
@tomwayson I totally had a response to this and then I must have closed the tab. The 2k limit affects both browsers and servers https://stackoverflow.com/questions/417142/what-is-the-maximum-length-of-a-url-in-different-browsers. We will run into the 2k limitation whenever we need to pass large JSON objects to the server not just with hosted services.

@tomwayson I don't agree with your logic about letting individual libraries choose to use `GET`. The implementation that @dbouwman did for [`searchItems`](https://github.com/Esri/arcgis-rest-js/blob/b052733184f4b6b74c6db82c473dad7aa2b6cc74/packages/arcgis-rest-items/src/items.ts#L44) could still hit URL length issues if you include a really complex query, an extent, ect... should be able to hit the 2000 character limit. Leaving this up to implementation in other modules doesn't seem very consistant and we could still run into cases where the request needs to be switch but the method doesn't implement switching.

If the main reason to switch to `GET` is debugging I can PR changes to use `application/x-www-form-urlencoded` wherever possible. Which makes the Chrome debugger display it like a `GET` request. The only time this won't occur is when using passing `Blob`, `Steam` or `File` objects as params which will require `multipart-form-data`.

![screenshot 2017-12-07 13 56 00](https://user-images.githubusercontent.com/378557/33740713-6a4580b4-db56-11e7-9ec0-a5a3115d3ed0.png)

**Comment by dbouwman** [comment]
I think the idea would be that the `arcgis-foo-lib` could have methods that recommend a `GET`, but the `request` fn still guard against O_o long query strings. 

So - by default, all things `POST`. Package authors can specify that -- if possible -- a `GET` should be used, but `request` will not let things explode, and will `POST` if needed.

The snippet below seems to need 2 lines added to address this...

```
return (authentication ? authentication.getToken(url) : Promise.resolve(""))
    .then(token => {
      if (token.length) {
        params.token = token;
      }

      if (httpMethod === "GET") {
        url = url + "?" + encodeQueryString(params);
        // check if url is long...
        if (url.length >= MAX_GET_LENGTH) {
               // if so, change to POST
               httpMethod = "POST"l
        }
      }

      if (httpMethod === "POST") {
        fetchOptions.body = encodeFormData(params);
      }

      return options.fetch(url, fetchOptions);
    })
```

**Comment by tomwayson** [comment]
I think #77 is a great step in the right direction, but I think we should do that _and_ add smart GET. Easier debugging is _a_ reason to switch to GET for queries, but not the only reason. Another is using the semantically correct HTTP verb, and the one that users expect to see for queries.

After #77 (and #78) lands, I'd like to PR something along the lines of what @dbouwman laid out above.
