### ISSUE TITLE
Shouldn't arcgis-rest-types should be a devDependency, and not dependency, of other packages?

### ISSUE THREAD

**Issue by tomwayson** [Esri/arcgis-rest-js#749]
https://github.com/Esri/arcgis-rest-js/pull/748#discussion_r483193124

**Comment by patrickarlt** [comment]
I think this still needs to be a `dependency` for when people use TypeScript. Conside something like `updateGroup()` types:

```ts
import { IRequestOptions } from "@esri/arcgis-rest-request";
import { IItemUpdate } from "@esri/arcgis-rest-types";
export interface IUpdateGroupOptions extends IRequestOptions {
    group: IItemUpdate;
}
/**
 * ```js
 * import { updateGroup } from '@esri/arcgis-rest-portal';
 * //
 * updateGroup({
 *   group: { id: "fgr344", title: "new" }
 * })
 *   .then(response)
 * ```
 * Update the properties of a group. See the [REST Documentation](https://developers.arcgis.com/rest/users-groups-and-items/update-group.htm) for more information.
 *
 * @param requestOptions - Options for the request, including the group
 * @returns A Promise that will resolve with the success/failure status of the request
 */
export declare function updateGroup(requestOptions: IUpdateGroupOptions): Promise<{
    success: boolean;
    groupId: string;
}>;
```

If `@esri/arcgis-rest-types` isn't installed (because it is a `devDependency`) TypeScript won't be able to find the types and compile.

We could maybe add it as an `optionalDependency` and advise people to install it for TypeScript where it is needed? There isn't really any harn in leaving it as a dependency since it doesn't affect anything for anyone.

**Comment by patrickarlt** [comment]
Closing this because we are removing `arcgis-rest-types` at 4.0
