### ISSUE TITLE
The toJSON method of UserSession excludes server property

### ISSUE THREAD

**Issue by dangrussell** [Esri/arcgis-rest-js#885]
When you use `UserSession.serialize(),` this does a `JSON.stringify()` of the object.

`JSON.stringify` obeys an object's `toJSON()` method, if present.

The `toJSON()` for `UserSession` excludes a few public properties of the object, like `server`, `federatedServers`, and `trustedDomains`.

So, this means that using `serialize()` (to put the object into storage, let's say) is destructive.

Furthermore, the `deserialize()` method is not strictly a `JSON.parse()`. It does a `JSON.parse()`, but then constructs a `UserSession` with enumerated properties, and `server` is not one of those enumerated properties.

The `server` property is lost in serializing and unserializing.

I'm using unfederated servers, so this is preventing me from restoring a valid `UserSession` from storage.

This seems wrong, but I'm relatively new to this API. If this is intentional, can someone help me understand why?

Thank you!

**Comment by patrickarlt** [comment]
@dangrussell It looks like `server` was missed in `toJSON()` and `deserialize()` when it was added in https://github.com/Esri/arcgis-rest-js/commit/fc2f06b74a40261ae9b6bb959048d353be02153b. I think we should serialize and deserialize `server` since it would be essential to storing a `UserSession`.

`federatedServers` and `trustedDomains` are a bit different. These function as internal caches depending on the requests made during the session. `federatedServers`  for example:

1. You create a `UserSession` and search a portal for some items.
2. You use the same `UserSession` to access the services in those items.
3. `federatedServers` will now contain a cache of the tokens generated for those services.

We COULD serialize and deserialize `federatedServers` but I think it is safer and more secure to only store the main token and let the federation step happen every time there is a new session.

* You store less critical information
* Servers might change or become unfederated
* Outside storing the `expires` there isn't a way to know if a token has become invalid.
* If the token IS invalid for some reason we throw and error we don't try to get a new token so it is probably more reliable to get a new token

For `trustedDomains` we fetch the domains from the portal on the first request of a `UserSession` and cache it for the remainder. If we allow deserialize to handle `trustedDomains` we would need a way of perodically making sure this didn't change which complicates the user session.

I'll get the issues with `server` resolved for our upcoming 4.0 release but you can work around this by doing your own serialize/deserialize


```js
import {UserSession} from "@esri/arcgis-rest-auth";

function serializeUserSessionWithServer(userSession) {
  return JSON.stringify({
      clientId: userSession.clientId,
      refreshToken: userSession.refreshToken,
      refreshTokenExpires: userSession.refreshTokenExpires,
      username: userSession.username,
      password: userSession.password,
      token: userSession.token,
      tokenExpires: userSession.tokenExpires,
      portal: userSession.portal,
      ssl: userSession.ssl,
      tokenDuration: userSession.tokenDuration,
      redirectUri: userSession.redirectUri,
      refreshTokenTTL: userSession.refreshTokenTTL,
      server: userSession.server
    })
}

function deserializeUserSessionWithServer(serializedUserSession) {
    const options = JSON.parse(serializedUserSession);
    return new UserSession({
      clientId: options.clientId,
      refreshToken: options.refreshToken,
      refreshTokenExpires: new Date(options.refreshTokenExpires),
      username: options.username,
      password: options.password,
      token: options.token,
      tokenExpires: new Date(options.tokenExpires),
      portal: options.portal,
      ssl: options.ssl,
      tokenDuration: options.tokenDuration,
      redirectUri: options.redirectUri,
      refreshTokenTTL: options.refreshTokenTTL,
      server: options.server,
    });
}
```

**Comment by dangrussell** [comment]
Thank you for the fix-up plan, the explanation of the differences, and the sample workaround code!

**Comment by patrickarlt** [comment]
Closing this. This will be part of the upcoming 4.0 release.
