### ISSUE TITLE
Add logic to allow sign-out (revoke token) for a UserSession

### ISSUE THREAD

**Issue by gavinr** [Esri/arcgis-rest-js#892]
The ArcGIS REST API now includes a [`/revokeToken` endpoint](https://developers.arcgis.com/rest/users-groups-and-items/revoke-token.htm).

> when a user signs out of the app so that no abandoned tokens are left valid.

**Comment by tomwayson** [comment]
related: #297

**Comment by tomwayson** [comment]
I think we should start by adding a standalone `revokeToken()` function that wraps that end point.

Then we should add `session.signOut()` that calls `revokeToken` for the access and/or refresh tokens that the session is holding.

**Comment by patrickarlt** [comment]
Reading the docs for the a [`/revokeToken` endpoint](https://developers.arcgis.com/rest/users-groups-and-items/revoke-token.htm) endpoint I think there are a few key things:

> An access token is issued from implicit grant and a refresh token can be revoked with this operation. 

This means that we can do 2 things:

* Revoke token granted by `beginOAuth2`/`completeOAuth2` cycle (implict grant)
* Revoke a refresh token and all associated tokens from `authorize`/`exchangeAuthorizationCode`

This also means (I think) that we cannot invalidate JUST an access token and force users to get a new token from their refresh token.

> Revoking an app access token and tokens generated from generate token are not supported with this operation.

So you cant revoke tokens from `ApplicationSession` or API keys with /revokeToken

---

I think because of these 2 things that this needs be a static `UserSession.destory()` or ``UserSession.signOut()`` method that calls `/revokeToken` for either the `refreshToken` (if available) or `token`. A generic `revokeToken` method could still be available but would need to clear that it only revoked the token in really specific situations.

**Comment by patrickarlt** [comment]
Closing this. This will be part of the upcoming 4.0 release.
