### ISSUE TITLE
Table ID field in IWebmap does not match webmap specification

### ISSUE THREAD

**Issue by dpbayer** [Esri/arcgis-rest-js#905]
For #808,  there has been a change to make the ITable.id  a number rather than a string.

This does not seem to be consistent with the published webmap specification
https://developers.arcgis.com/web-map-specification/objects/table/

https://github.com/Esri/arcgis-rest-js/blob/master/packages/arcgis-rest-types/src/webmap.ts#L498
https://github.com/Esri/arcgis-rest-js/blob/master/packages/arcgis-rest-types/src/webmap.ts#L458

The following has been taken from a newly created map in the new MapViewer.
```json
  }
  ],
  "tables": [
    {
      "id": "17ba6193830-layer-6",
      "title": "LinearFRelPoint",
      "url": ".....",
      "itemId": "3ae9f...."
```

**Comment by dpbayer** [comment]
Yes...  Based on the webmap spec from the website, and looking at the json of a webmap saved with the MapViewer, it should be a string.

ITable.ID maybe used in other places, but in the context of the webmap it should be a string.

**Comment by gavinr** [comment]
Ah, so it sounds maybe the issue is that `ITable` is used both:

- [In `IFeatureServiceDefinition`](https://github.com/Esri/arcgis-rest-js/blob/b99814bd20254739fffb2f3aae362a4a2f26896d/packages/arcgis-rest-types/src/service.ts#L77)
- [In IWebmap](https://github.com/Esri/arcgis-rest-js/blob/b99814bd20254739fffb2f3aae362a4a2f26896d/packages/arcgis-rest-types/src/webmap.ts#L498)

... but the problem is that they may be slightly different:

- In this issue you are bringing up the fact that `IWebmap` table ID should be a string
- [issue 808 was saying](https://github.com/Esri/arcgis-rest-js/issues/808) that the `IFeatureServiceDefinition` table ID should be a number. 

So maybe we need to split `ITable` into `IWebmapTable` and `IFeatureServiceDefinitionTable` or something like that. It would be nice to know if there are other differences other than the type of the ID.
